spring:
  application:
    name: zuul

server:
  port: 8769
  max-http-header-size: 102400
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    authenticate:
      path: /authenticate/**
      serviceId: authenticate

  ignored-services: "*"
  sensitive-headers:
  host:
    connect-timeout-millis: 200000
    socket-timeout-millis: 200000
feign:
  httpclient:
    connection-timeout: 100000
    enabled: true
  hystrix:
    enabled: true
mybatis:
    mapper-locations: classpath:/mapperXML/*.xml
    configuration:
      cache-enabled: true

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000