server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.106.215.35:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
    type-aliases-package: cn.zx.common.entity
    mapper-locations: classpath:mapper/*.xml

